name: simple_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0-281.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  drift: ^2.18.0
  path: ^1.9.0
  path_provider: ^2.1.3
  sqlite3_flutter_libs: ^0.5.24
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  go_router: ^14.2.0
  get_it: ^7.7.0
  mocktail: ^1.0.4
  rx_shared_preferences: ^3.1.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  drift_dev: ^2.18.0
  test: ^1.25.7
  bloc_test: ^9.1.7
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
